import json
import math
import os
import re
import string
import uuid
from collections import Counter
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_PATH = "audit_log.jsonl"
CERT_PATH = "certificates.json"


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def log_event(entry: dict) -> None:
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(limit: int = 20) -> list:
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []
    return [json.loads(line) for line in lines[-limit:]]


def find_log_entry(content_id: str) -> dict | None:
    """Return the most recent non-appeal log entry for content_id, or None."""
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return None
    for line in reversed(lines):
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            return entry
    return None


def update_log_status(content_id: str, new_status: str) -> None:
    """Rewrite the log file updating status on all entries matching content_id."""
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return
    updated = []
    for line in lines:
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            entry["status"] = new_status
        updated.append(json.dumps(entry) + "\n")
    with open(LOG_PATH, "w") as f:
        f.writelines(updated)


def read_all_log() -> list:
    try:
        with open(LOG_PATH) as f:
            return [json.loads(line) for line in f.readlines()]
    except FileNotFoundError:
        return []


# ---------------------------------------------------------------------------
# Certificate store helpers (STRETCH: provenance certificate)
# ---------------------------------------------------------------------------

def load_certificates() -> dict:
    try:
        with open(CERT_PATH) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def save_certificates(certs: dict) -> None:
    with open(CERT_PATH, "w") as f:
        json.dump(certs, f, indent=2)


def get_certificate(creator_id: str) -> dict | None:
    return load_certificates().get(creator_id)


# ---------------------------------------------------------------------------
# Signal 1: LLM classification via Groq
# ---------------------------------------------------------------------------

def signal_llm(text: str, content_type: str = "text") -> float:
    """Return a float 0–1 representing AI-generation probability per the LLM."""
    if content_type == "image_description":
        type_context = (
            "an image description or alt-text caption. "
            "AI-generated descriptions tend to be formulaic: "
            "'A [adjective] [noun] [verb phrase] against a [adjective] background.' "
            "Human descriptions are more idiosyncratic, personal, or emotionally specific."
        )
    else:
        type_context = (
            "a piece of prose writing (poem, story, blog post, essay). "
            "Look for uniform hedging language, overly structured paragraph flow, "
            "absence of personal voice, and consistent formal register."
        )

    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

You are analyzing {type_context}

Estimate the probability that the following content was generated by an AI writing tool.

Respond ONLY with a valid JSON object in this exact format, with no other text:
{{"ai_probability": <float between 0.0 and 1.0>}}

Where:
- 0.0 means you are certain this was written/composed by a human
- 1.0 means you are certain this was generated by an AI

Content to analyze:
\"\"\"
{text}
\"\"\"
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )

    raw = response.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    parsed = json.loads(raw)
    score = float(parsed["ai_probability"])
    return max(0.0, min(1.0, score))


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def signal_stylometric(text: str, content_type: str = "text") -> float:
    """Return a float 0–1 representing AI-generation probability via stylometrics."""
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())
    non_standard = set("—–…;()!?")

    # --- 1. Sentence length variance ------------------------------------------
    # For image descriptions (often one sentence), down-weight this sub-metric.
    if len(sentences) < 2:
        variance_score = 0.5
    else:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)
        variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # For image descriptions, halve the weight of sentence variance
    variance_weight = 0.5 if content_type == "image_description" else 1.0

    # --- 2. Type-token ratio (TTR) --------------------------------------------
    if len(words) == 0:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.35)))

    # --- 3. Punctuation diversity ---------------------------------------------
    total_punct = sum(1 for ch in text if ch in string.punctuation)
    diverse_punct = sum(1 for ch in text if ch in non_standard)
    if total_punct == 0:
        punct_score = 0.5
    else:
        diversity_ratio = diverse_punct / total_punct
        punct_score = max(0.0, min(1.0, 1.0 - (diversity_ratio / 0.3)))

    if content_type == "image_description":
        # Sentence variance is unreliable for single-sentence captions; use 0.5 neutral
        stylo_score = (0.5 * variance_weight + ttr_score + punct_score) / (variance_weight + 2.0)
    else:
        stylo_score = (variance_score + ttr_score + punct_score) / 3.0

    return round(stylo_score, 4)


# ---------------------------------------------------------------------------
# Signal 3: N-gram repetition rate (STRETCH — ensemble detection)
# ---------------------------------------------------------------------------

def signal_ngram(text: str) -> float:
    """Return a float 0–1 representing AI-generation probability via n-gram repetition.

    AI text reuses bigram and trigram phrase patterns at higher rates than human
    writing because generation is driven by learned token co-occurrence probabilities.
    Human writing is more inventive at the phrase level.

    Method: count how many distinct bigrams and trigrams appear more than once,
    divided by the total number of distinct n-grams. Higher repetition → more AI-like.
    """
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())
    if len(words) < 4:
        return 0.5  # too short to measure reliably

    bigrams = [tuple(words[i:i+2]) for i in range(len(words) - 1)]
    trigrams = [tuple(words[i:i+3]) for i in range(len(words) - 2)]
    all_ngrams = bigrams + trigrams

    if not all_ngrams:
        return 0.5

    counts = Counter(all_ngrams)
    total_distinct = len(counts)
    repeated = sum(1 for c in counts.values() if c > 1)

    repetition_ratio = repeated / total_distinct if total_distinct > 0 else 0.0

    # Calibration: ratio >= 0.35 is very repetitive (AI-like); 0.0 is fully unique (human)
    ngram_score = max(0.0, min(1.0, repetition_ratio / 0.35))
    return round(ngram_score, 4)


# ---------------------------------------------------------------------------
# Confidence scoring — weighted ensemble (STRETCH updates weighting to 3 signals)
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float,
                       ngram_score: float | None = None) -> float:
    """Combine signals into a single confidence score (higher = more AI-like).

    3-signal ensemble (when ngram_score is provided):
      LLM 50% + Stylometric 30% + N-gram 20%

    Conflict resolution: if LLM and stylometric disagree by > 0.4, shift
    weight further toward the LLM (semantic judgment is more reliable when
    structural signals conflict with meaning-level signals).
    """
    if ngram_score is None:
        return round((0.60 * llm_score) + (0.40 * stylo_score), 4)

    disagreement = abs(llm_score - stylo_score)
    if disagreement > 0.4:
        # Shift: LLM 65%, stylometric 20%, n-gram 15%
        confidence = (0.65 * llm_score) + (0.20 * stylo_score) + (0.15 * ngram_score)
    else:
        confidence = (0.50 * llm_score) + (0.30 * stylo_score) + (0.20 * ngram_score)

    return round(confidence, 4)


def attribution_from_confidence(confidence: float) -> str:
    if confidence < 0.35:
        return "likely_human"
    elif confidence <= 0.65:
        return "uncertain"
    else:
        return "likely_ai"


def generate_label(confidence: float) -> str:
    if confidence < 0.35:
        return (
            "This content shows strong indicators of human authorship. "
            "Our analysis found writing patterns consistent with a person "
            "rather than an AI writing tool."
        )
    elif confidence <= 0.65:
        return (
            "This content may have been written by a person, an AI tool, "
            "or a combination of both. Our system was not able to make a "
            "confident determination. The creator can submit an appeal to "
            "provide additional context."
        )
    else:
        return (
            "This content was likely generated by an AI writing tool. "
            "Our analysis found strong indicators of AI authorship based on "
            "writing style and structure. If you are the creator and believe "
            "this is incorrect, you can submit an appeal."
        )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True)
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "unknown")
    content_type = data.get("content_type", "text")  # "text" or "image_description"

    if not text:
        return jsonify({"error": "text field is required"}), 400
    if content_type not in ("text", "image_description"):
        return jsonify({"error": "content_type must be 'text' or 'image_description'"}), 400

    content_id = str(uuid.uuid4())

    llm_score = signal_llm(text, content_type)
    stylo_score = signal_stylometric(text, content_type)
    ngram_score = signal_ngram(text)
    confidence = compute_confidence(llm_score, stylo_score, ngram_score)
    attribution = attribution_from_confidence(confidence)
    label_text = generate_label(confidence)

    # Check for provenance certificate (STRETCH)
    cert = get_certificate(creator_id)
    certificate_info = None
    if cert:
        certificate_info = {
            "badge": "Verified Human Author",
            "verified_at": cert["verified_at"],
            "note": "This creator has completed human verification for a prior submission.",
        }

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "content_type": content_type,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "ngram_score": ngram_score,
        "status": "classified",
        "certificate": cert is not None,
    })

    response = {
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "ngram_score": ngram_score,
        "label_text": label_text,
        "content_type": content_type,
        "status": "classified",
    }
    if certificate_info:
        response["certificate"] = certificate_info

    return jsonify(response)


@app.route("/log", methods=["GET"])
def view_log():
    limit = request.args.get("limit", 20, type=int)
    return jsonify({"entries": read_log(limit)})


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True)
    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    original = find_log_entry(content_id)
    if original is None:
        return jsonify({"error": "content_id not found"}), 404

    update_log_status(content_id, "under_review")

    log_event({
        "content_id": content_id,
        "event": "appeal",
        "creator_reasoning": creator_reasoning,
        "original_attribution": original.get("attribution"),
        "original_confidence": original.get("confidence"),
        "status": "under_review",
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and is under review. "
                   "A human reviewer will assess your content and the reasoning you provided.",
    })


# ---------------------------------------------------------------------------
# STRETCH: Provenance certificate
# ---------------------------------------------------------------------------

@app.route("/verify", methods=["POST"])
def verify():
    """Creator submits a verification answer about their content to earn a certificate."""
    data = request.get_json(force=True)
    content_id = data.get("content_id", "").strip()
    creator_id = data.get("creator_id", "").strip()
    verification_answer = data.get("verification_answer", "").strip()

    if not content_id or not creator_id or not verification_answer:
        return jsonify({
            "error": "content_id, creator_id, and verification_answer are all required"
        }), 400

    original = find_log_entry(content_id)
    if original is None:
        return jsonify({"error": "content_id not found"}), 404

    if original.get("creator_id") != creator_id:
        return jsonify({"error": "creator_id does not match the original submission"}), 403

    if len(verification_answer.strip()) < 20:
        return jsonify({
            "error": "verification_answer is too short. Describe something specific "
                     "about your creative process or context that only the author would know."
        }), 400

    # Store certificate keyed by creator_id
    certs = load_certificates()
    certs[creator_id] = {
        "creator_id": creator_id,
        "verified_content_id": content_id,
        "verification_answer": verification_answer,
        "verified_at": datetime.now(timezone.utc).isoformat(),
    }
    save_certificates(certs)

    log_event({
        "content_id": content_id,
        "event": "verification",
        "creator_id": creator_id,
        "status": "verified",
    })

    return jsonify({
        "creator_id": creator_id,
        "certificate": "Verified Human Author",
        "verified_content_id": content_id,
        "verified_at": certs[creator_id]["verified_at"],
        "message": "Verification complete. Your 'Verified Human Author' badge will appear "
                   "on all future content submissions.",
    })


@app.route("/certificate/<content_id>", methods=["GET"])
def certificate(content_id: str):
    """Return certificate status for a given content_id."""
    original = find_log_entry(content_id)
    if original is None:
        return jsonify({"error": "content_id not found"}), 404

    creator_id = original.get("creator_id")
    cert = get_certificate(creator_id)

    if cert:
        return jsonify({
            "content_id": content_id,
            "creator_id": creator_id,
            "certificate": "Verified Human Author",
            "verified_at": cert["verified_at"],
            "badge_text": (
                "This creator has earned a Verified Human Author certificate by "
                "completing a knowledge challenge that demonstrates personal authorship. "
                "This badge is distinct from the standard attribution analysis."
            ),
        })
    else:
        return jsonify({
            "content_id": content_id,
            "creator_id": creator_id,
            "certificate": None,
            "message": "This creator has not completed human verification.",
        })


# ---------------------------------------------------------------------------
# STRETCH: Analytics dashboard
# ---------------------------------------------------------------------------

@app.route("/analytics", methods=["GET"])
def analytics():
    """Return detection patterns, appeal rate, and average confidence by category."""
    all_entries = read_all_log()

    classified = [e for e in all_entries if e.get("event") != "appeal"
                  and e.get("event") != "verification"
                  and e.get("attribution") is not None]
    appeals = [e for e in all_entries if e.get("event") == "appeal"]

    total = len(classified)
    appeal_count = len(appeals)

    counts = {"likely_human": 0, "uncertain": 0, "likely_ai": 0}
    confidence_sums = {"likely_human": 0.0, "uncertain": 0.0, "likely_ai": 0.0}

    for e in classified:
        attr = e.get("attribution")
        if attr in counts:
            counts[attr] += 1
            confidence_sums[attr] += e.get("confidence", 0.0)

    detection_pattern = {}
    avg_confidence = {}
    for attr in ("likely_human", "uncertain", "likely_ai"):
        n = counts[attr]
        detection_pattern[attr] = {
            "count": n,
            "percentage": round((n / total * 100), 1) if total > 0 else 0.0,
        }
        avg_confidence[attr] = round(confidence_sums[attr] / n, 4) if n > 0 else None

    appeal_rate = round(appeal_count / total * 100, 1) if total > 0 else 0.0

    return jsonify({
        "total_submissions": total,
        "detection_pattern": detection_pattern,
        "appeal_rate": {
            "appeal_count": appeal_count,
            "percentage": appeal_rate,
        },
        "average_confidence_by_attribution": avg_confidence,
    })


if __name__ == "__main__":
    app.run(port=5001, debug=True)
