import json
import math
import os
import re
import string
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_PATH = "audit_log.jsonl"


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def log_event(entry: dict) -> None:
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(limit: int = 20) -> list:
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []
    return [json.loads(line) for line in lines[-limit:]]


def find_log_entry(content_id: str) -> dict | None:
    """Return the most recent log entry matching content_id, or None."""
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return None
    for line in reversed(lines):
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            return entry
    return None


def update_log_status(content_id: str, new_status: str) -> None:
    """Rewrite the log file updating status on all entries matching content_id."""
    try:
        with open(LOG_PATH) as f:
            lines = f.readlines()
    except FileNotFoundError:
        return
    updated = []
    for line in lines:
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            entry["status"] = new_status
        updated.append(json.dumps(entry) + "\n")
    with open(LOG_PATH, "w") as f:
        f.writelines(updated)


# ---------------------------------------------------------------------------
# Signal 1: LLM classification via Groq
# ---------------------------------------------------------------------------

def signal_llm(text: str) -> float:
    """Return a float 0–1 representing AI-generation probability per the LLM."""
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and estimate the probability that it was generated by an AI writing tool.

Respond ONLY with a valid JSON object in this exact format, with no other text:
{{"ai_probability": <float between 0.0 and 1.0>}}

Where:
- 0.0 means you are certain this was written by a human
- 1.0 means you are certain this was generated by an AI

Text to analyze:
\"\"\"
{text}
\"\"\"
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    parsed = json.loads(raw)
    score = float(parsed["ai_probability"])
    return max(0.0, min(1.0, score))


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def signal_stylometric(text: str) -> float:
    """Return a float 0–1 representing AI-generation probability via stylometrics.

    Three sub-metrics are computed and normalized so that higher values
    mean more AI-like. They are averaged into a single stylo_score.

    Sub-metrics:
      1. Sentence length variance  — AI text is more uniform (low variance → high score)
      2. Type-token ratio (TTR)    — AI text is less lexically diverse (low TTR → high score)
      3. Punctuation diversity     — AI text uses fewer non-standard marks (low diversity → high score)
    """
    # --- 1. Sentence length variance ------------------------------------------
    # Split on sentence-ending punctuation; keep non-empty chunks.
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        # Too short to measure variance — treat as neutral
        variance_score = 0.5
    else:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)
        # High std_dev → more human-like → lower AI score.
        # Clamp: std_dev >= 8 words is very human; 0 is perfectly uniform (AI).
        variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # --- 2. Type-token ratio (TTR) --------------------------------------------
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # High TTR → more human-like → lower AI score.
        # TTR of 1.0 (all unique) is very human; ~0.5 is very AI-like.
        # Normalize: below 0.5 → AI score near 1; above 0.85 → AI score near 0.
        ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.35)))

    # --- 3. Punctuation diversity ---------------------------------------------
    # Non-standard marks: em dash, en dash, ellipsis, semicolon, parentheses,
    # exclamation (mid-text), question mark (mid-text), colon (non-list usage).
    non_standard = set("—–…;()!?")
    total_punct = sum(1 for ch in text if ch in string.punctuation)
    diverse_punct = sum(1 for ch in text if ch in non_standard)
    if total_punct == 0:
        punct_score = 0.5
    else:
        diversity_ratio = diverse_punct / total_punct
        # High diversity → more human-like → lower AI score.
        # Clamp: ratio >= 0.3 is quite human; 0 means only periods/commas (AI-like).
        punct_score = max(0.0, min(1.0, 1.0 - (diversity_ratio / 0.3)))

    stylo_score = (variance_score + ttr_score + punct_score) / 3.0
    return round(stylo_score, 4)


# ---------------------------------------------------------------------------
# Confidence scoring and attribution
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float) -> float:
    """Combine signals into a single confidence score (higher = more AI-like).

    LLM signal weighted at 60%: captures semantic/stylistic coherence holistically.
    Stylometric signal weighted at 40%: captures structural statistical properties.
    """
    return round((0.60 * llm_score) + (0.40 * stylo_score), 4)


def attribution_from_confidence(confidence: float) -> str:
    if confidence < 0.35:
        return "likely_human"
    elif confidence <= 0.65:
        return "uncertain"
    else:
        return "likely_ai"


def generate_label(confidence: float) -> str:
    if confidence < 0.35:
        return (
            "This content shows strong indicators of human authorship. "
            "Our analysis found writing patterns consistent with a person "
            "rather than an AI writing tool."
        )
    elif confidence <= 0.65:
        return (
            "This content may have been written by a person, an AI tool, "
            "or a combination of both. Our system was not able to make a "
            "confident determination. The creator can submit an appeal to "
            "provide additional context."
        )
    else:
        return (
            "This content was likely generated by an AI writing tool. "
            "Our analysis found strong indicators of AI authorship based on "
            "writing style and structure. If you are the creator and believe "
            "this is incorrect, you can submit an appeal."
        )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True)
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "unknown")

    if not text:
        return jsonify({"error": "text field is required"}), 400

    content_id = str(uuid.uuid4())

    llm_score = signal_llm(text)
    stylo_score = signal_stylometric(text)
    confidence = compute_confidence(llm_score, stylo_score)
    attribution = attribution_from_confidence(confidence)
    label_text = generate_label(confidence)

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "label_text": label_text,
        "status": "classified",
    })


@app.route("/log", methods=["GET"])
def view_log():
    limit = request.args.get("limit", 20, type=int)
    return jsonify({"entries": read_log(limit)})


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True)
    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    original = find_log_entry(content_id)
    if original is None:
        return jsonify({"error": "content_id not found"}), 404

    update_log_status(content_id, "under_review")

    log_event({
        "content_id": content_id,
        "event": "appeal",
        "creator_reasoning": creator_reasoning,
        "original_attribution": original.get("attribution"),
        "original_confidence": original.get("confidence"),
        "status": "under_review",
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and is under review. "
                   "A human reviewer will assess your content and the reasoning you provided.",
    })


if __name__ == "__main__":
    app.run(port=5001, debug=True)
